version: '3.8'

services:
  web:
    build: .
    ports:
      - 9000:9000
    command: ['honcho', 'start','-f', 'Procfile.dev']
    volumes:
      - .:/usr/src/app
    env_file:
      - ./app/.env
    container_name: beequizer
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.worker.celery worker --loglevel=info
    volumes:
      - .:/usr/src/app
    env_file:
      - ./app/.env
    container_name: celery-worker
    depends_on:
      - web
      - redis

  redis:
    image: redis:7
    container_name: redis

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - 6333:6333
    volumes:
      - sb_dms_qdrant_data:/qdrant/data
    environment:
      - QDRANT_API_KEY=qdrant
  
volumes:
  sb_dms_qdrant_data:


    
